// <auto-generated />
using System;
using Digital.Net.Cms.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Digital.Net.Cms.Migrations
{
    [DbContext(typeof(CmsContext))]
    [Migration("20260320233851_forms")]
    partial class forms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("digital_net_cms")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<Guid>("ArticlesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("ArticlesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ArticleTag", "digital_net_cms");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Name");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("Published");

                    b.Property<string>("SubmitLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("SubmitLabel");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Form", "digital_net_cms");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.FormField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DefaultValue");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("FormId");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("Name");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text")
                        .HasColumnName("OptionsJson");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Placeholder");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("Required");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("SortOrder");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("Type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("ValidationJson")
                        .HasColumnType("text")
                        .HasColumnName("ValidationJson");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormField", "digital_net_cms");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.FormSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("FormId");

                    b.Property<string>("SubmitterIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("SubmitterIp");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("UserAgent");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ValuesJson");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormSubmission", "digital_net_cms");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Alt")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("Alt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("DocumentId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Name");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("Published");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Media", "digital_net_cms");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.MediaVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("DocumentId");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("Height");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("MediaId");

                    b.Property<int>("Quality")
                        .HasColumnType("integer")
                        .HasColumnName("Quality");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("Width");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Width", "Quality")
                        .IsUnique();

                    b.ToTable("MediaVariant", "digital_net_cms");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("Description");

                    b.Property<bool>("Indexed")
                        .HasColumnType("boolean")
                        .HasColumnName("Indexed");

                    b.Property<string>("JsonLd")
                        .HasMaxLength(65535)
                        .HasColumnType("character varying(65535)")
                        .HasColumnName("JsonLd");

                    b.Property<string>("OpenGraph")
                        .HasMaxLength(65535)
                        .HasColumnType("character varying(65535)")
                        .HasColumnName("OpenGraph");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2068)
                        .HasColumnType("character varying(2068)")
                        .HasColumnName("Path");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("Published");

                    b.Property<string>("Redirect")
                        .HasMaxLength(2068)
                        .HasColumnType("character varying(2068)")
                        .HasColumnName("Redirect");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Page", "digital_net_cms");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.PageSheet", b =>
                {
                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("PageId");

                    b.Property<Guid>("SheetId")
                        .HasColumnType("uuid")
                        .HasColumnName("SheetId");

                    b.Property<int>("LoadOrder")
                        .HasColumnType("integer")
                        .HasColumnName("LoadOrder");

                    b.HasKey("PageId", "SheetId");

                    b.HasIndex("SheetId");

                    b.ToTable("PageSheet", "digital_net_cms");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.Sheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Name");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("Published");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("Type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Sheet", "digital_net_cms");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Tag", "digital_net_cms");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.Article", b =>
                {
                    b.HasBaseType("Digital.Net.Cms.Models.Page");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Name");

                    b.ToTable("Article", "digital_net_cms");
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("Digital.Net.Cms.Models.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital.Net.Cms.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.FormField", b =>
                {
                    b.HasOne("Digital.Net.Cms.Models.Form", "Form")
                        .WithMany("Fields")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.FormSubmission", b =>
                {
                    b.HasOne("Digital.Net.Cms.Models.Form", "Form")
                        .WithMany("Submissions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.MediaVariant", b =>
                {
                    b.HasOne("Digital.Net.Cms.Models.Media", "Media")
                        .WithMany("Variants")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.PageSheet", b =>
                {
                    b.HasOne("Digital.Net.Cms.Models.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital.Net.Cms.Models.Sheet", "Sheet")
                        .WithMany("PageSheets")
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.Article", b =>
                {
                    b.HasOne("Digital.Net.Cms.Models.Page", null)
                        .WithOne()
                        .HasForeignKey("Digital.Net.Cms.Models.Article", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.Form", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.Media", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Digital.Net.Cms.Models.Sheet", b =>
                {
                    b.Navigation("PageSheets");
                });
#pragma warning restore 612, 618
        }
    }
}
